<?php
if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}

return array(
	'name' => esc_html__( 'construction home service 1', 'themetonaddon' ),
	'image_path' => 'http://themeton.com/themetonaddon/themeton-vc-blocks/'.basename(dirname(__FILE__)).'/'.'construction-home-service1.jpg',
	'cat_display_name' => 'services',
	'custom_class' => 'tt_vc_templates-1',
	'content' => <<<CONTENT
[vc_row content_placement="middle" vc_row_container="uk-container" vc_row_flex="uk-flex" vc_row_themeton="yes" css=".vc_custom_1496735562023{padding-top: 100px !important;padding-bottom: 0px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column width="1/2" css=".vc_custom_1496734861574{padding-top: 30px !important;}"][vc_custom_heading text="Our Services" font_container="tag:h2|font_size:34|text_align:left" google_fonts="font_family:Playfair%20Display%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:700%20bold%20regular%3A700%3Anormal"][vc_row_inner content_placement="middle" css=".vc_custom_1496734951994{padding-top: 80px !important;}"][vc_column_inner width="1/2"][vc_single_image image="1792" img_size="290x250" onclick="zoom" css_animation="fadeIn"][/vc_column_inner][vc_column_inner width="1/2"][vc_custom_heading text="Plannig Creation" font_container="tag:h2|text_align:justify" google_fonts="font_family:Playfair%20Display%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:700%20bold%20regular%3A700%3Anormal"][vc_column_text]Lorem Ipsum is simply dummy text of the printing typesetting industry. Lorem Ipsum has been the industry's standard.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/2"][vc_row_inner content_placement="middle"][vc_column_inner width="1/2"][vc_single_image image="1278" img_size="290x250" onclick="zoom" css_animation="fadeIn"][/vc_column_inner][vc_column_inner width="1/2"][vc_custom_heading text="Interior Designing" font_container="tag:h2|text_align:justify" google_fonts="font_family:Playfair%20Display%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:700%20bold%20regular%3A700%3Anormal"][vc_column_text]Lorem Ipsum is simply dummy text of the printing typesetting industry. Lorem Ipsum has been the industry's standard.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row content_placement="middle" vc_row_container="uk-container" vc_row_valignment="uk-flex-middle" vc_row_flex="uk-flex" vc_row_themeton="yes" css=".vc_custom_1496734757788{padding-top: 40px !important;padding-bottom: 55px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column width="1/3"][vc_custom_heading text="Full</br>
Services" font_container="tag:h2|font_size:24px|text_align:left|color:%23f54983" google_fonts="font_family:Playfair%20Display%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:400%20regular%3A400%3Anormal" link="url:http%3A%2F%2Fnext.themeton.com%2Fconstruction%2Fservice%2Fservice-column-3%2F|||" el_class="hover-underline"][/vc_column][vc_column width="2/3"][vc_row_inner content_placement="middle"][vc_column_inner width="1/3"][vc_single_image image="1279" img_size="320x270" onclick="zoom" css_animation="fadeIn"][/vc_column_inner][vc_column_inner width="1/3"][vc_custom_heading text="Interior Designing" font_container="tag:h2|text_align:justify" google_fonts="font_family:Playfair%20Display%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:700%20bold%20regular%3A700%3Anormal"][vc_column_text]Lorem Ipsum is simply dummy text of the printing typesetting industry. Lorem Ipsum has been the industry's standard.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT
);