<?php
if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}

return array(
	'name' => esc_html__( 'Logistics Opening', 'themetonaddon' ),
	'image_path' => 'http://themeton.com/themetonaddon/themeton-vc-blocks/'.basename(dirname(__FILE__)).'/'.'logistics-opening.jpg',
	'cat_display_name' => 'services',
	'custom_class' => 'mungu_vc_templates-1',
	'content' => <<<CONTENT
[vc_row][vc_column css=".vc_custom_1491463002316{margin-bottom: 40px !important;}"][vc_custom_heading text="Current Opening" font_container="tag:h2|font_size:30px|text_align:left" use_theme_fonts="yes" css=".vc_custom_1491464934490{margin-bottom: 5px !important;}" el_class="text-600 dash"][/vc_column][/vc_row][vc_row css=".vc_custom_1488608750996{padding-bottom: 17px !important;}"][vc_column width="1/2"][vc_row_inner][vc_column_inner width="1/2"][info_box icon_type="fontawesome" icon_fontawesome="fa fa-smile-o" shadows="medium" href="url:%23|||" icons="fa fa-smile-o" title="Fun Environment"][/vc_column_inner][vc_column_inner width="1/2"][info_box size="42px" icon_type="fontawesome" icon_fontawesome="fa fa-coffee" shadows="medium" href="url:%23|||" icons="fa fa-coffee" title="Unlimited Coffee"][/vc_column_inner][/vc_row_inner][vc_row_inner css=".vc_custom_1491462582699{margin-top: 30px !important;}"][vc_column_inner width="1/2"][info_box size="42px" icon_type="fontawesome" icon_fontawesome="fa fa-gift" shadows="medium" href="url:%23|||" icons="fa fa-gift" title="Compensation"][/vc_column_inner][vc_column_inner width="1/2"][info_box size="42px" icon_type="fontawesome" icon_fontawesome="fa fa-rocket" shadows="medium" href="url:%23|||" extra_class="hahah" icons="fa fa-rocket" title="Pleasure Trips"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/2" css=".vc_custom_1491463475997{margin-left: 30px !important;}"][vc_column_text]
<p style="text-align: left">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>

[/vc_column_text][vc_row_inner][vc_column_inner width="1/3" css=".vc_custom_1491463441013{margin-top: 20px !important;}"][vc_custom_heading text="16+ Available" font_container="tag:h2|font_size:24px|text_align:left|color:%23ff5e00|line_height:24px" use_theme_fonts="yes" link="url:http%3A%2F%2Fnext.themeton.com%2Flogistics%2F||target:%20_blank|" css=".vc_custom_1491546042605{border-bottom-width: 1px !important;border-bottom-color: #ff5e00 !important;border-bottom-style: solid !important;}" el_class="no-decoration"][vc_custom_heading text="Vacancies" font_container="tag:h2|font_size:24px|text_align:left|color:%23ff5e00|line_height:24px" use_theme_fonts="yes" link="url:http%3A%2F%2Fnext.themeton.com%2Flogistics%2F||target:%20_blank|" css=".vc_custom_1491546047725{margin-top: -10px !important;border-bottom-width: 1px !important;border-bottom-color: #ff5e00 !important;border-bottom-style: solid !important;}" el_class="no-decoration"][/vc_column_inner][vc_column_inner width="1/3"][/vc_column_inner][vc_column_inner width="1/3"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT
);