<?php
if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}

return array(
	'name' => esc_html__( 'carrental about service', 'themetonaddon' ),
	'image_path' => 'http://themeton.com/themetonaddon/themeton-vc-blocks/'.basename(dirname(__FILE__)).'/'.'carrental-about-service.jpg',
	'cat_display_name' => 'services',
	'custom_class' => 'mungu_vc_templates-1',
	'content' => <<<CONTENT
[vc_section full_width="stretch_row_content" css=".vc_custom_1506482365898{padding-top: 100px !important;padding-bottom: 100px !important;background-color: #00b2ca !important;}"][vc_row el_class="uk-text-center"][vc_column el_class="uk-light"][vc_custom_heading text="Advantages" font_container="tag:h2|font_size:36|text_align:center|color:%23ffffff|line_height:1" use_theme_fonts="yes" css=".vc_custom_1510886943846{margin-bottom: 0px !important;}"][vc_custom_heading text="You know about our specialties" font_container="tag:h4|text_align:center|color:%23ffffff" use_theme_fonts="yes" el_class="dash" css=".vc_custom_1510887297518{padding-bottom: 40px !important;}"][/vc_column][/vc_row][vc_row content_placement="middle" vc_row_container="uk-container" css=".vc_custom_1506424280727{padding-top: 0px !important;padding-bottom: 0px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column css=".vc_custom_1506425489620{padding-top: 0px !important;}" el_class="custom-class-for-vc"][carousel_anythings slidetype="container" items="5" items_desktop_small="5" arrow_show="false" stop_on_hover="true"][vc_row_inner el_class="vr-border"][vc_column_inner el_class="vr-border"][vc_single_image image="1875" alignment="center" css=".vc_custom_1506484651007{margin-bottom: 15px !important;padding-bottom: 0px !important;}"][vc_custom_heading text="Door Step Delivery" font_container="tag:h3|font_size:28|text_align:center|color:%23ffffff|line_height:30px" google_fonts="font_family:Alegreya%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:400%20regular%3A400%3Anormal" css=".vc_custom_1510916777244{margin-top: 0px !important;margin-bottom: 0px !important;}" link="url:http%3A%2F%2Fnext.themeton.com%2Fcarrental%2Fservice-item%2Fdamage-insurance%2F|||"][/vc_column_inner][/vc_row_inner][vc_row_inner el_class="vr-border"][vc_column_inner el_class="vr-border"][vc_single_image image="1877" alignment="center" css=".vc_custom_1506484674223{margin-bottom: 15px !important;padding-bottom: 0px !important;}"][vc_custom_heading text="No Hidden<br />
Charges" font_container="tag:h3|font_size:28|text_align:center|color:%23ffffff|line_height:30px" google_fonts="font_family:Alegreya%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:400%20regular%3A400%3Anormal" css=".vc_custom_1510916880896{margin-top: 0px !important;margin-bottom: 0px !important;}" link="url:http%3A%2F%2Fnext.themeton.com%2Fcarrental%2Fservice-item%2Fdamage-insurance%2F|||"][/vc_column_inner][/vc_row_inner][vc_row_inner el_class="vr-border"][vc_column_inner el_class="vr-border"][vc_single_image image="1876" alignment="center" css=".vc_custom_1506484690261{margin-bottom: 15px !important;padding-bottom: 0px !important;}"][vc_custom_heading text="Go<br />
Anywhere" font_container="tag:h3|font_size:28|text_align:center|color:%23ffffff|line_height:30px" google_fonts="font_family:Alegreya%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:400%20regular%3A400%3Anormal" css=".vc_custom_1510916867812{margin-top: 0px !important;margin-bottom: 0px !important;}" link="url:http%3A%2F%2Fnext.themeton.com%2Fcarrental%2Fservice-item%2Fdamage-insurance%2F|||"][/vc_column_inner][/vc_row_inner][vc_row_inner el_class="vr-border"][vc_column_inner el_class="vr-border"][vc_single_image image="1886" alignment="center" css=".vc_custom_1506484737856{margin-bottom: 15px !important;padding-bottom: 0px !important;}"][vc_custom_heading text="Best Price<br />
Guarantee" font_container="tag:h3|font_size:28|text_align:center|color:%23ffffff|line_height:30px" google_fonts="font_family:Alegreya%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:400%20regular%3A400%3Anormal" css=".vc_custom_1510916899932{margin-top: 0px !important;margin-bottom: 0px !important;}" link="url:http%3A%2F%2Fnext.themeton.com%2Fcarrental%2Fservice-item%2Fdamage-insurance%2F|||"][/vc_column_inner][/vc_row_inner][vc_row_inner el_class="vr-border"][vc_column_inner el_class="vr-border"][vc_single_image image="1874" alignment="center" css=".vc_custom_1506484834692{margin-bottom: 15px !important;padding-bottom: 0px !important;}"][vc_custom_heading text="Damage<br />
Insurance" font_container="tag:h3|font_size:28|text_align:center|color:%23ffffff|line_height:30px" google_fonts="font_family:Alegreya%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:400%20regular%3A400%3Anormal" css=".vc_custom_1510916910797{margin-top: 0px !important;margin-bottom: 0px !important;}" link="url:http%3A%2F%2Fnext.themeton.com%2Fcarrental%2Fservice-item%2Fdamage-insurance%2F|||"][/vc_column_inner][/vc_row_inner][/carousel_anythings][/vc_column][/vc_row][/vc_section]

CONTENT
);