<?php
if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}

return array(
	'name' => esc_html__( 'Medical Services Details', 'themetonaddon' ),
	'image_path' => 'http://themeton.com/themetonaddon/themeton-vc-blocks/'.basename(dirname(__FILE__)).'/'.'medical-services-details.jpg',
	'cat_display_name' => 'contents',
	'custom_class' => 'mungu_vc_templates-1',
	'content' => <<<CONTENT
[vc_row css=".vc_custom_1517895733015{margin-right: 5px !important;margin-bottom: 30px !important;margin-left: 1px !important;padding-top: 200px !important;padding-bottom: 200px !important;background-image: url(http://next.themeton.com/church/wp-content/uploads/sites/11/2017/06/event4-1.jpg?id=868) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][/vc_column][/vc_row][vc_row][vc_column][vc_row_inner][vc_column_inner width="1/6"][/vc_column_inner][vc_column_inner width="2/3"][vc_column_text]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.[/vc_column_text][vc_custom_heading text="Special Features" font_container="tag:h4|text_align:left" use_theme_fonts="yes"][icon_list icon_type="fontawesome" icon_fontawesome="fa fa-long-arrow-right" color="rgba(0,0,0,0.5)" list="%5B%7B%22item%22%3A%22Donec%20ut%20nibh%20anunc%20congueauctor%20eget%20velodio.%20%22%7D%2C%7B%22item%22%3A%22Morbi%20atnibhsit%20ametrisus%20laoreet%20iaculis%20vitae%20pharetra%20nibh.%20%22%7D%2C%7B%22item%22%3A%22Vestibulum%20idante%20id%20augue%20tincidunt%20tincidunt%20egetvel%20metus.%20%22%7D%2C%7B%22item%22%3A%22Praesent%20aliquamante%20vitaedolor%20commodo%20ullamcorper.%22%7D%5D"][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][mungu_team carousel="" input_type="post"][vc_row_inner css=".vc_custom_1491369143764{margin-top: 20px !important;}"][vc_column_inner width="1/6"][/vc_column_inner][vc_column_inner width="2/6"][vc_column_text]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled[/vc_column_text][/vc_column_inner][vc_column_inner width="2/6"][vc_column_text]when an unknown printer took a galley of type and scrambled it to make a type specimen book. Has survived not only five centuries, but also the leap into electronic.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][vc_row_inner css=".vc_custom_1491224110587{margin-bottom: 100px !important;}"][vc_column_inner width="1/6"][/vc_column_inner][vc_column_inner width="2/6"][con_button conbutton="url:http%3A%2F%2Fdemo.themeton.com%2Fmedical%2Fpages%2Fappointment%2F|title:BOOK%20CONSULTATION||"][/vc_column_inner][vc_column_inner width="2/6"][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]

CONTENT
);