<?php
if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}

return array(
	'name' => esc_html__( 'yoga footer', 'themetonaddon' ),
	'image_path' => 'http://themeton.com/themetonaddon/themeton-vc-blocks/'.basename(dirname(__FILE__)).'/'.'yoga-footer.jpg',
	'cat_display_name' => 'Header & Footer',
	'custom_class' => 'mungu_vc_templates-1',
	'content' => <<<CONTENT
[vc_row full_width="stretch_row" css=".vc_custom_1515143953775{padding-top: 165px !important;padding-bottom: 15px !important;background-image: url(http://next.themeton.com/yoga/wp-content/uploads/sites/24/2017/12/Footer.png?id=282) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column width="2/3" css=".vc_custom_1515143584469{margin-top: 35px !important;}"][menu menu="None"][vc_row_inner][vc_column_inner width="1/3" css=".vc_custom_1515143315267{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 22px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"][vc_raw_html css=".vc_custom_1515143225161{margin-bottom: 0px !important;}"]JTNDdWwlMjBjbGFzcyUzRCUyMnlmb290ZXItaWNvbiUyMiUyMHN0eWxlJTNEJTIycGFkZGluZyUzQSUyMDAlM0IlMjBsaXN0LXN0eWxlLXR5cGUlM0ElMjBub25lJTNCJTIyJTNFJTBBJTIwJTIwJTIwJTIwJTNDbGklM0UlMjAlM0NhJTIwaHJlZiUzRCUyMiUyMyUyMiUzRSUzQ2ltZyUyMHNyYyUzRCUyMmh0dHAlM0ElMkYlMkZuZXh0LnRoZW1ldG9uLmNvbSUyRnlvZ2ElMkZ3cC1jb250ZW50JTJGdXBsb2FkcyUyRnNpdGVzJTJGMjQlMkYyMDE3JTJGMTIlMkZmYWNlYm9vay5wbmclMjIlMkYlM0UlM0MlMkZhJTNFJTNDJTJGbGklM0UlMEElMjAlMjAlMjAlMjAlM0NsaSUzRSUyMCUzQ2ElMjBocmVmJTNEJTIyJTIzJTIyJTNFJTNDaW1nJTIwc3JjJTNEJTIyaHR0cCUzQSUyRiUyRm5leHQudGhlbWV0b24uY29tJTJGeW9nYSUyRndwLWNvbnRlbnQlMkZ1cGxvYWRzJTJGc2l0ZXMlMkYyNCUyRjIwMTclMkYxMiUyRnR3aXR0ZXIucG5nJTIyJTJGJTNFJTNDJTJGYSUzRSUzQyUyRmxpJTNFJTBBJTIwJTIwJTIwJTIwJTNDbGklM0UlMjAlM0NhJTIwaHJlZiUzRCUyMiUyMyUyMiUzRSUzQ2ltZyUyMHNyYyUzRCUyMmh0dHAlM0ElMkYlMkZuZXh0LnRoZW1ldG9uLmNvbSUyRnlvZ2ElMkZ3cC1jb250ZW50JTJGdXBsb2FkcyUyRnNpdGVzJTJGMjQlMkYyMDE3JTJGMTIlMkZ2aW1lby5wbmclMjIlMkYlM0UlM0MlMkZhJTNFJTNDJTJGbGklM0UlMEElMjAlMjAlMjAlMjAlM0NsaSUzRSUyMCUzQ2ElMjBocmVmJTNEJTIyJTIzJTIyJTNFJTNDaW1nJTIwc3JjJTNEJTIyaHR0cCUzQSUyRiUyRm5leHQudGhlbWV0b24uY29tJTJGeW9nYSUyRndwLWNvbnRlbnQlMkZ1cGxvYWRzJTJGc2l0ZXMlMkYyNCUyRjIwMTclMkYxMiUyRnlvdXR1YmUucG5nJTIyJTJGJTNFJTNDJTJGYSUzRSUzQyUyRmxpJTNFJTBBJTNDJTJGdWwlM0U=[/vc_raw_html][/vc_column_inner][vc_column_inner width="2/3"][vc_custom_heading text="Copyright © 2017. next All rights reserved" font_container="tag:p|font_size:16px|text_align:left|color:%23c5c5c5|line_height:65px" use_theme_fonts="yes" css=".vc_custom_1515143413915{margin-left: -30px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/3" css=".vc_custom_1515143841845{padding-top: 112px !important;}"][vc_custom_heading text="Mungu." font_container="tag:h2|font_size:35px|text_align:right|color:%23ffffff|line_height:35px" google_fonts="font_family:Roboto%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C700%2C700italic%2C900%2C900italic|font_style:500%20bold%20regular%3A500%3Anormal"][/vc_column][/vc_row]
CONTENT
);