<?php
if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}

return array(
	'name' => esc_html__( 'Creative testimonials c7', 'themetonaddon' ),
	'image_path' => 'http://themeton.com/themetonaddon/themeton-vc-blocks/'.basename(dirname(__FILE__)).'/'.'c7.jpg',
	'cat_display_name' => 'testimonials',
	'custom_class' => 'mungu_vc_templates-1',
	'content' => <<<CONTENT
[vc_row full_width="stretch_row_content" equal_height="yes" content_placement="middle"][vc_column width="1/3" css=".vc_custom_1504757406647{padding-top: 100px !important;padding-bottom: 80px !important;background-color: #08263d !important;}"][vc_single_image image="757" alignment="center" style="vc_box_circle_2"][vc_separator color="custom" el_width="10" accent_color="rgba(255,255,255,0.5)"][vc_icon icon_fontawesome="fa fa-camera-retro" color="white" size="lg" align="center" css_animation="fadeInUp" link="url:%23|title:Click%20me||" css=".vc_custom_1504756892365{margin-bottom: 0px !important;}"][vc_custom_heading text="PHOTOGRAPHER" font_container="tag:h4|font_size:18px|text_align:center|color:%23ffffff|line_height:1" use_theme_fonts="yes" css_animation="fadeInUp" link="url:%23|title:Click%20me||" css=".vc_custom_1504757055126{margin-top: 10px !important;margin-bottom: 50px !important;}"][vc_icon icon_fontawesome="fa fa-pencil" color="white" size="lg" align="center" css_animation="fadeInUp" link="url:%23|title:Click%20me||" css=".vc_custom_1504756939780{margin-bottom: 0px !important;}"][vc_custom_heading text="WRITER" font_container="tag:h4|font_size:18px|text_align:center|color:%23ffffff|line_height:1" use_theme_fonts="yes" css_animation="fadeInUp" link="url:%23|title:Click%20me||" css=".vc_custom_1504757060391{margin-top: 10px !important;margin-bottom: 50px !important;}"][vc_icon icon_fontawesome="fa fa-plane" color="white" size="lg" align="center" css_animation="fadeInUp" link="url:%23|title:Click%20me||" css=".vc_custom_1504756998670{margin-bottom: 0px !important;}"][vc_custom_heading text="TRAVELER" font_container="tag:h4|font_size:18px|text_align:center|color:%23ffffff|line_height:1" use_theme_fonts="yes" css_animation="fadeInUp" link="url:%23|title:Click%20me||" css=".vc_custom_1504757065940{margin-top: 10px !important;margin-bottom: 50px !important;}"][/vc_column][vc_column width="2/3" css=".vc_custom_1504757276473{padding-right: 150px !important;padding-left: 150px !important;}"][vc_custom_heading text="QUICKLY INNOVATE CENTURY
	VISIONARY MODELS DRAMATICALLY" font_container="tag:h2|font_size:20px|text_align:left|line_height:1.2" google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal"][vc_separator color="custom" accent_color="rgba(0,0,0,0.15)"][vc_column_text]Progressively provide access to just in time paradigms with dynamic e-business. Holisticly disseminate market-driven internal or "organic" sources whereas client-centered networks. Intrinsicly mesh an expanded. Progressively enhance 24/7 outsourcing vis-a-vis frictionless interfaces. Rapidiously parallel task user friendly communities with dynamic web services. Credibly empower revolutionary growth strategies vis-a-vis user-centric communities.[/vc_column_text][vc_column_text]
	<blockquote class="minimal">I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.</blockquote>
	[/vc_column_text][vc_column_text]Appropriately redefine collaborative portals for client-centric products. Holisticly reintermediate tactical manufactured products before top-line resources. Seamlessly strategize economically sound e-markets vis-a-vis covalent e-commerce. Completely scale. Progressively enhance 24/7 outsourcing vis-a-vis frictionless interfaces. Rapidiously parallel task user friendly communities with dynamic web services. Credibly empower revolutionary growth strategies vis-a-vis user-centric communities.[/vc_column_text][vc_custom_heading text="http://mydomain.com/aboutme" font_container="tag:p|font_size:18px|text_align:left" use_theme_fonts="yes" link="url:%23|title:Click%20me||" css=".vc_custom_1504757888460{border-bottom-width: 1px !important;border-bottom-color: #212121 !important;border-bottom-style: solid !important;}" el_class="uk-inline"][/vc_column][/vc_row]
CONTENT
);